using UnityEngine;
using UnityEngine.InputSystem;

/**
 * This component moves its object when the player clicks the arrow keys.
 */
public class InputMover : MonoBehaviour
{
    [Tooltip("Speed of movement, in meters per second")]
    [SerializeField]
    private float speed = 10f;

    [SerializeField]
    private InputAction move = new InputAction(
        type: InputActionType.Value,
        expectedControlType: nameof(Vector2));

    private void OnEnable()
    {
        move.Enable();
    }

    private void OnDisable()
    {
        move.Disable();
    }

    private void Update()
    {
        Vector2 moveDirection = move.ReadValue<Vector2>();
        Vector3 movementVector =
            new Vector3(moveDirection.x, moveDirection.y, 0) * speed * Time.deltaTime;

        transform.position += movementVector;

        // NOTE: "Translate(movementVector)" uses relative coordinates -
        //       it moves the object in the coordinate system of the object itself.
        // In contrast, "transform.position += movementVector" uses world coordinates.
        // It makes a difference only if the object is rotated.
    }
}
