using UnityEngine;
using UnityEngine.SceneManagement;

public class GotoNextLevel : MonoBehaviour
{
    [SerializeField]
    private string triggeringTag;

    [SerializeField]
    [Tooltip("Name of scene to move to when triggering the given tag")]
    private string sceneName;

    // [SerializeField] NumberField scoreField;

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.tag == triggeringTag)
        {
            Debug.Log("Moving " + this + " to zero");
            transform.position = Vector3.zero;

            // Input can either be a serial number or a name; here we use name.
            SceneManager.LoadScene(sceneName);
        }
    }
}
